### ISSUE TITLE
Missing About

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/dp-420-cosmos-db-dev.ko-KR#37]
Missing the information in "About" field.

Missing the Link to "Github Pages"
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/64255878/157817701-089e75c6-7043-40da-9c6c-05d5660af7ca.png)

**Comment by stonezy123** [comment]
not loclization issue

**Comment by olprod** [comment]
![image](https://user-images.githubusercontent.com/16075726/184617129-5f299960-5ece-4c9a-a1c1-683112c6930d.png)
