### ISSUE TITLE
03-migrate-data.md - extra bold tag present

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/dp-420-cosmos-db-dev.ko-KR#40]
In this doc, in the first Task, Step 21, there are two extra bold tags at the end:

**크기 조정 및 설정** 노드를 선택합니다. **크기 조정 및 설정** 탭에서 **수동**을 선택하고 **필수 처리량** 설정을 **4000RU/s**에서 **400RU/s**로 업데이트한 다음, 변경 내용을 **저장**합니다**.

(addt'l ** bold tags at end)

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
[Locfiles ](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5UcnVlPC9TSFJQPjxTQVRPPlRydWU8L1NBVE8%2bPFNBTE8%2bRmFsc2U8L1NBTE8%2bPFFFPj4yPC9RRT48UVQ%2bPjxRUiBJZD0iMSIgQ1BJRD0iMCI%2bQ3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgU3RvcmU7RXF1YWw7V1dMPC9RUj48UVIgSWQ9IjIiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgQXNzZXQgSUQ7RXF1YWw7MDMtbWlncmF0ZS1kYXRhLm1kPC9RUj48UVIgSWQ9IjMiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0xvY0ZpbGVzO0xhbmd1YWdlO0VxdWFsO0tvcmVhbiAoS29yZWEpPC9RUj48L1FUPjxSRz48R0M%2bTlVMTDwvR0M%2bPC9SRz48L1ZQUT4%3d)in question

**Comment by chriscarty00** [comment]
Updating the HB locfile as this will see the TM and the fix will be taken to the newer Locfile when it hands-off - agreed with the PM 
Update made
